# custom composite action
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Get & Cache Dependencies"
description: "Get the dependencies(via npm) and cache them"
inputs:
  # key name that is up to you
  caching:
    description: " whether to cache dep or not"
    required: false
    default: "true"
# key name that is up to you
outputs:
  used-cache:
  description: 'Whether the cache was used.'
# connect value with id in the install dep. step
  value: ${{ steps.install.outputs.cache }}

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: 
      npm ci
      echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      # if we using run key we need to use shell key
      shell: bash
